name: Zip & Deploy Nijisanji Subfolders

on:
  push:
    paths:
      - 'Nijisanji/**'
  schedule:
    - cron: '0 0 * * *'

jobs:
  zip_and_upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Zip each subfolder
        run: |
          cd Nijisanji
          for dir in */; do
            folder=${dir%/}
            zip -r "../${folder}.zip" "$folder"
          done

      - name: Upload ZIP artifacts
        uses: actions/upload-artifact@v4  # ここを v3 から v4 に更新
        with:
          name: Nijisanji-Zips
          path: '*.zip'

