# .github/workflows/zip-nijisanji-folders.yml
name: Zip & Deploy Nijisanji Subfolders

on:
  # コード変更時にも動かす
  push:
    paths:
      - 'Nijisanji/**'
  # スケジュール実行
  schedule:
    # UTC の毎日00:00に実行する場合
    - cron: '0 0 * * *'
    # ↓日本時間0:00に実行したい場合はこちらを有効に
    # - cron: '0 15 * * *'

jobs:
  zip_and_upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Zip each subfolder
        run: |
          cd Nijisanji
          for dir in */; do
            folder=${dir%/}
            zip -r "../${folder}.zip" "$folder"
          done

      - name: Upload ZIP artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Nijisanji-Zips
          path: '*.zip'

